Fix bad source code version in release

diff --git a/.github/workflows/deliv_extlib_openradioss_ci.yaml b/.github/workflows/deliv_extlib_openradioss_ci.yaml
--- a/.github/workflows/deliv_extlib_openradioss_ci.yaml
+++ b/.github/workflows/deliv_extlib_openradioss_ci.yaml
@@ -182,7 +182,7 @@ jobs:
           git branch && git log --pretty=oneline -n 5
           echo "-------"      
 
-          # # Opensource libs
+          # Opensource libs
           # jf rt download ${JF_OPTIONS} --flat=true --recursive --exclusions="*/_com/*" "${{ env.HM_REMOTE_DIR }}/(*)" ${HMREADER_OPENSOURCE_LOCAL_DIR}/{1}
 
           # Get current date in YYYY-MM-DD format
@@ -208,62 +208,54 @@ jobs:
 
           echo "Committing new version file to v${current_version}"
 
-      #     git commit -m "Update extlib version to v${current_version}"
+          git commit -m "Update extlib version to v${current_version}"
 
-      #     # Create zip for asset
-      #     cp ${{ env.VERSION_FILE }} extlib/
-      #     zip -r extlib.zip extlib
+          # Create zip for asset
+          # cp ${{ env.VERSION_FILE }} extlib/
+          echo "File 1" > extlib/file1.txt
+          echo "File 2" > extlib/file2.txt
+          zip -r extlib.zip extlib
 
-      #     if [[ -n $(git status --porcelain) ]]; then
-      #       # Set correct end of step status (if not an email will be sent)
-      #       echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
-      #       echo "GO_PUSH=1" >> $GITHUB_ENV
-      #     else
-      #       echo "There are no changes in the repository, abort."
-      #       exit 1
-      #     fi
+          if [[ -n $(git status --porcelain) ]]; then
+            # Set correct end of step status (if not an email will be sent)
+            echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
+            echo "GO_PUSH=1" >> $GITHUB_ENV
+          else
+            echo "There are no changes in the repository, abort."
+            exit 1
+          fi
 
-      # - name: Push changes
-      #   uses: ad-m/github-push-action@master
-      #   if: ${{ env.GO_PUSH == 1 }} 
-      #   with:
-      #     github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
-      #     branch: ${{ github.ref }}     
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        if: ${{ env.GO_PUSH == 1 }} 
+        with:
+          github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
+          branch: ${{ github.ref }}     
 
-      # - name: Set push status
-      #   run: |    
-      #     # Set correct end of step status (if not an email will be sent)
-      #     echo "STATUS_STEP_PUSH=1" >> $GITHUB_ENV
+      - name: Set push status
+        run: |    
+          # Set correct end of step status (if not an email will be sent)
+          echo "STATUS_STEP_PUSH=1" >> $GITHUB_ENV
 
-      # - name: Create fake extlib for testing
-      #   run: |    
-      #     rm -rf extlib
-      #     mkdir -p extlib
-      #     echo "File 1" > extlib/file1.txt
-      #     echo "File 2" > extlib/file2.txt
-      #     zip -r extlib.zip extlib
-      #     echo "STATUS_STEP_PUSH=1" >> $GITHUB_ENV  
-      #     echo "EXTLIB_VERSION=36" >> $GITHUB_ENV    
+      # The action creates the release with an already existing tag (latest-xxxxx) so we use option skip_tag_creation: true
+      # We do this because we have already checkouted the wanted commit before
+      # Prerequisite: create the tag with command : git tag latest-YYYMMDD <commit id>; git push origin latest-YYYMMDD
+      - name: Release the new binaries
+        uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          tag: "v${{ env.EXTLIB_VERSION }}"
+          name: "Extlib v${{ env.EXTLIB_VERSION }}"            
+          body: |
+            Find here last ext libs for radioss including hmreader in version v${{ env.EXTLIB_VERSION }} delivered on ${{ env.CURRENT_DATE }}
+          files: |
+            extlib.zip
+          clear_attachments: true    
 
-      # # The action creates the release with an already existing tag (latest-xxxxx) so we use option skip_tag_creation: true
-      # # We do this because we have already checkouted the wanted commit before
-      # # Prerequisite: create the tag with command : git tag latest-YYYMMDD <commit id>; git push origin latest-YYYMMDD
-      # - name: Release the new binaries
-      #   uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
-      #   with:
-      #     token: ${{ secrets.GITHUB_TOKEN }}
-      #     tag: "v${{ env.EXTLIB_VERSION }}"
-      #     name: "Extlib v${{ env.EXTLIB_VERSION }}"            
-      #     body: |
-      #       Find here last ext libs for radioss including hmreader in version v${{ env.EXTLIB_VERSION }} delivered on ${{ env.CURRENT_DATE }}
-      #     files: |
-      #       extlib.zip
-      #     clear_attachments: true    
-
-      # - name: Set release creation status
-      #   run: |    
-      #     # Set correct end of step status (if not an email will be sent)
-      #     echo "STATUS_STEP_CREATE_RELEASE=1" >> $GITHUB_ENV
+      - name: Set release creation status
+        run: |    
+          # Set correct end of step status (if not an email will be sent)
+          echo "STATUS_STEP_CREATE_RELEASE=1" >> $GITHUB_ENV
 
       # # Trigger OpenRadioss CI to set the new version of extlib and cause a build/qa
       # - name: Trigger OpenRadioss CI
