Test release create with attachment

diff --git a/.github/workflows/deliv_extlib_openradioss_ci.yaml b/.github/workflows/deliv_extlib_openradioss_ci.yaml
--- a/.github/workflows/deliv_extlib_openradioss_ci.yaml
+++ b/.github/workflows/deliv_extlib_openradioss_ci.yaml
@@ -68,162 +68,78 @@ jobs:
 
     steps:
 
-      # # Set the working dir suffixed with deliv_extlib
-      # - name: Set workdir and status
-      #   run: |
-      #     echo "WORKDIR=deliv_extlib" >> $GITHUB_ENV
-      #     echo "WORKDIR_OR=deliv_extlib_openradioss" >> $GITHUB_ENV
-      #     echo "DELIVERY_STATUS=0" >> $GITHUB_ENV
- 
-      # - name: Create specific deliv extlib oriented WS directory
-      #   run: |
-      #     mkdir -p ${{ env.WORKDIR }} ${{ env.WORKDIR_OR }}
+      - name: Checking delivery commit
+        run: |
+          # Get branch
+          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
 
-      # - name: Checking delivery commit
-      #   working-directory: ${{ env.WORKDIR }}
-      #   run: |
-      #     # Get branch
-      #     export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
 
-      #     echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
-
-      #     # DEV ONLY #
-      #     # export BRANCH_NAME="dev/ci/hm_reader_intermediate"
+          # DEV ONLY #
+          # export BRANCH_NAME="dev/ci/hm_reader_intermediate"
           
-      #     export HM_REMOTE_DIR="${HW_SOLVER_PREFIX}/${HMREADER_PREFIX}/${BRANCH_NAME}/${DELIV_COMMIT}"
-      #     echo "HM_REMOTE_DIR=${HM_REMOTE_DIR}" >> $GITHUB_ENV
-      #     # Check if the commit exist on jfrog
-      #     result_hm=$(jf rt s ${JF_OPTIONS} "${HM_REMOTE_DIR}/*")
+          export HM_REMOTE_DIR="${HW_SOLVER_PREFIX}/${HMREADER_PREFIX}/${BRANCH_NAME}/${DELIV_COMMIT}"
+          echo "HM_REMOTE_DIR=${HM_REMOTE_DIR}" >> $GITHUB_ENV
+          # Check if the commit exist on jfrog
+          result_hm=$(jf rt s ${JF_OPTIONS} "${HM_REMOTE_DIR}/*")
 
-      #     if [[ "${result_hm}" == "[]" ]]
-      #     then
-      #       echo "Commit ${DELIV_COMMIT} does not exist on Jfrog."
-      #       exit 1
-      #     fi
+          if [[ "${result_hm}" == "[]" ]]
+          then
+            echo "Commit ${DELIV_COMMIT} does not exist on Jfrog."
+            exit 1
+          fi
 
-      #     # Set correct end of step status (if not an email will be sent)
-      #     echo "STATUS_STEP_CHECK_DELIV_COMMIT=1" >> $GITHUB_ENV          
+          # Set correct end of step status (if not an email will be sent)
+          echo "STATUS_STEP_CHECK_DELIV_COMMIT=1" >> $GITHUB_ENV          
 
-      # - name: Check all libs are present
-      #   run: |     
-      #     echo "-------------------------"
-      #     echo "Verify libraries on jfrog"
-      #     echo "-------------------------"
+      - name: Check all libs are present
+        run: |     
+          echo "-------------------------"
+          echo "Verify libraries on jfrog"
+          echo "-------------------------"
 
-      #     patterns=(
-      #       "linux64/libhm_reader_linux64.so"
-      #       "linuxa64/libhm_reader_linuxa64.so"
-      #       "win64/hm_reader_win64.lib"
-      #       "win64/hm_reader_win64.dll"
-      #     )
+          patterns=(
+            "linux64/libhm_reader_linux64.so"
+            "linuxa64/libhm_reader_linuxa64.so"
+            "win64/hm_reader_win64.lib"
+            "win64/hm_reader_win64.dll"
+          )
 
-      #     result_array=$(jf rt search ${JF_OPTIONS} ${{ env.HM_REMOTE_DIR }}/* | grep '"path":' | sed 's/.*"path": "//' | sed 's/",//')
+          result_array=$(jf rt search ${JF_OPTIONS} ${{ env.HM_REMOTE_DIR }}/* | grep '"path":' | sed 's/.*"path": "//' | sed 's/",//')
 
-      #     all_found=true
-      #     not_found_libs=''
+          all_found=true
+          not_found_libs=''
 
-      #     # Loop through each pattern
-      #     for pattern in "${patterns[@]}"; do
-      #         # Check if the pattern is present in any line
-      #         found=false
-      #         for line in "${result_array[@]}"; do
-      #             if echo "$line" | grep -q "$pattern"; then
-      #                 found=true
-      #                 break
-      #             fi
-      #         done
+          # Loop through each pattern
+          for pattern in "${patterns[@]}"; do
+              # Check if the pattern is present in any line
+              found=false
+              for line in "${result_array[@]}"; do
+                  if echo "$line" | grep -q "$pattern"; then
+                      found=true
+                      break
+                  fi
+              done
 
-      #         # If the pattern was not found in any line, mark as not all found
-      #         if ! $found; then
-      #             # echo "Pattern '$pattern' not found in any line."
-      #             not_found_libs+="\n${pattern}"
-      #             all_found=false
-      #         # else
-      #         #     echo "Pattern '$pattern' found."
-      #         fi
-      #     done
+              # If the pattern was not found in any line, mark as not all found
+              if ! $found; then
+                  # echo "Pattern '$pattern' not found in any line."
+                  not_found_libs+="\n${pattern}"
+                  all_found=false
+              # else
+              #     echo "Pattern '$pattern' found."
+              fi
+          done
 
-      #     # Final result check
-      #     if $all_found; then
-      #         echo -e "\nAll librarie have been found!"
-      #         # Set correct end of step status (if not an email will be sent)
-      #         echo "STATUS_STEP_CHECK_LIBS=1" >> $GITHUB_ENV
-      #     else
-      #         echo -e "\nSome librariy pattern has not been found:\n${not_found_libs}"
-      #         exit 1
-      #     fi
-
-      # # Get last git modifications
-      # - name: Checkout git sources
-      #   uses: actions/checkout@v4
-      #   with:
-      #     path: ${{ env.WORKDIR }}
-      #     clean: 'true'
-      #     # Use a PAT else the push won't trigger the next workflow
-      #     token: ${{ env.GIT_PUSH_SERVBOT_PAT }}          
-
-      # - name: Get hm reader libs locally
-      #   working-directory: ${{ env.WORKDIR }}
-      #   run: |
-      #     echo "--------------"
-      #     echo "Getting HM Reader files"
-      #     echo "----------"
-
-      #     # Force local branch to point on same commit as remote branch, way to restore a correct env if old push failed before
-      #     git fetch origin ${BRANCH_NAME}
-      #     git reset --hard origin/${BRANCH_NAME}
-      #     # git lfs install
-      #     echo "-------checkout"
-      #     git branch && git log --pretty=oneline -n 5
-      #     echo "-------"      
-
-      #     # # Opensource libs
-      #     # jf rt download ${JF_OPTIONS} --flat=true --recursive --exclusions="*/_com/*" "${{ env.HM_REMOTE_DIR }}/(*)" ${HMREADER_OPENSOURCE_LOCAL_DIR}/{1}
-
-      #     # Get current version in VERSION_FILE
-      #     current_version=$(grep -oP 'extlib v\K[0-9]+' ${{ env.VERSION_FILE }})
-      #     current_version=$((current_version + 1))
-      #     echo "Current version is: ${current_version}"
-      #     echo "extlib v${current_version}" > ${{ env.VERSION_FILE }}
-      #     echo "EXTLIB_VERSION=${current_version}" >> $GITHUB_ENV
-
-      #     # # Add new files
-      #     # git config --global user.email "${{ env.GIT_SERVBOT_EMAIL }}"
-      #     # git config --global user.name "${{ env.GIT_SERVBOT_USER }}"
-      #     # git add ${{ env.VERSION_FILE }}
-      #     # git status
-
-      #     # git commit -m "Update extlib version to v${current_version}"
-
-      #     # Create zip for asset
-      #     # zip -r extlib.zip extlib
-
-      #     # if [[ -n $(git status --porcelain) ]]; then
-      #     #   # Set correct end of step status (if not an email will be sent)
-      #     #   echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
-      #     #   echo "GO_PUSH=1" >> $GITHUB_ENV
-      #     # else
-      #     #   echo "There are no changes in the repository, abort."
-      #     #   exit 1
-      #     # fi
-
-      #     # TO REMOVE
-      #     echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
-
-      # # - name: Push changes
-      # #   uses: ad-m/github-push-action@master
-      # #   if: ${{ env.GO_PUSH == 1 }} 
-      # #   with:
-      # #     github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
-      # #     branch: ${{ github.ref }}     
-      # #     directory: ${{ env.WORKDIR }}    
-
-      # - name: Set push status
-      #   working-directory: ${{ env.WORKDIR }}
-      #   run: |    
-      #     # Set correct end of step status (if not an email will be sent)
-      #     echo "STATUS_STEP_PUSH=1" >> $GITHUB_ENV
-
+          # Final result check
+          if $all_found; then
+              echo -e "\nAll librarie have been found!"
+              # Set correct end of step status (if not an email will be sent)
+              echo "STATUS_STEP_CHECK_LIBS=1" >> $GITHUB_ENV
+          else
+              echo -e "\nSome librariy pattern has not been found:\n${not_found_libs}"
+              exit 1
+          fi
 
       # Get last git modifications
       - name: Checkout git sources
@@ -231,7 +147,68 @@ jobs:
         with:
           clean: 'true'
           # Use a PAT else the push won't trigger the next workflow
-          token: ${{ env.GIT_PUSH_SERVBOT_PAT }}    
+          token: ${{ env.GIT_PUSH_SERVBOT_PAT }}          
+
+      - name: Get hm reader libs locally
+        run: |
+          echo "--------------"
+          echo "Getting HM Reader files"
+          echo "----------"
+
+          # Force local branch to point on same commit as remote branch, way to restore a correct env if old push failed before
+          git fetch origin ${BRANCH_NAME}
+          git reset --hard origin/${BRANCH_NAME}
+          # git lfs install
+          echo "-------checkout"
+          git branch && git log --pretty=oneline -n 5
+          echo "-------"      
+
+          # # Opensource libs
+          # jf rt download ${JF_OPTIONS} --flat=true --recursive --exclusions="*/_com/*" "${{ env.HM_REMOTE_DIR }}/(*)" ${HMREADER_OPENSOURCE_LOCAL_DIR}/{1}
+
+          # Get current version in VERSION_FILE
+          current_version=$(grep -oP 'extlib v\K[0-9]+' ${{ env.VERSION_FILE }})
+          current_version=$((current_version + 1))
+          echo "Current version is: ${current_version}"
+          echo "extlib v${current_version}" > ${{ env.VERSION_FILE }}
+          echo "EXTLIB_VERSION=${current_version}" >> $GITHUB_ENV
+
+          # Add new files
+          git config --global user.email "${{ env.GIT_SERVBOT_EMAIL }}"
+          git config --global user.name "${{ env.GIT_SERVBOT_USER }}"
+          git add ${{ env.VERSION_FILE }}
+          git status
+
+          git commit -m "Update extlib version to v${current_version}"
+
+          Create zip for asset
+          zip -r extlib.zip extlib
+
+          if [[ -n $(git status --porcelain) ]]; then
+            # Set correct end of step status (if not an email will be sent)
+            echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
+            echo "GO_PUSH=1" >> $GITHUB_ENV
+          else
+            echo "There are no changes in the repository, abort."
+            exit 1
+          fi
+
+          # # TO REMOVE
+          # echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
+
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        if: ${{ env.GO_PUSH == 1 }} 
+        with:
+          github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
+          branch: ${{ github.ref }}     
+          directory: ${{ env.WORKDIR }}    
+
+      - name: Set push status
+        working-directory: ${{ env.WORKDIR }}
+        run: |    
+          # Set correct end of step status (if not an email will be sent)
+          echo "STATUS_STEP_PUSH=1" >> $GITHUB_ENV
 
       # The action creates the release with an already existing tag (latest-xxxxx) so we use option skip_tag_creation: true
       # We do this because we have already checkouted the wanted commit before
@@ -241,14 +218,13 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release: "Extlib v$EXTLIB_VERSION"
-          tag: "vA"
+          tag: "v$EXTLIB_VERSION"
           name: "Extlib v$EXTLIB_VERSION"            
           body: |
             Find here last ext libs for radioss including hmreader
-          # files: |
-          #   ${{ env.WORKDIR }}/extlib.zip
+          files: |
+            extlib.zip
           clear_attachments: true    
-          # target_commit: ${{ env.LAST_STABLE_COMMIT }}
 
       - name: Set release creation status
         working-directory: ${{ env.WORKDIR }}
